version: '3'
services:
  server:
    build: .
    ports:
      - "8080:8080"
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - server
    networks:
      - app-network
networks:
  app-network:
    driver: bridge