version: '3'
services:
  proxy-server:
    build: .
    ports:
      - "8080:8080"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - proxy-server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge