version: "3"
services:
  server:
    build: ./server
    ports:
      - "8080:8080"
    volumes:
      - letsencrypt:/etc/letsencrypt

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - server
    volumes:
      - letsencrypt:/etc/letsencrypt
      - certbot-webroot:/var/www/certbot

  certbot:
    build: ./certbot
    volumes:
      - letsencrypt:/etc/letsencrypt
      - certbot-webroot:/var/www/certbot
    environment:
      - CERTBOT_EMAIL=kirillvegele10@gmail.com
      - CERTBOT_DOMAIN=192.168.1.33

volumes:
  letsencrypt:
  certbot-webroot:
